INSERT INTO schools (school_name, school_code) VALUES ('Admiralty Primary School', 'P_Admiralty');
INSERT INTO schools (school_name, school_code) VALUES ('Ahmad Ibrahim Primary School', 'P_Ahmad');
INSERT INTO schools (school_name, school_code) VALUES ('Ai Tong School', 'P_Ai');
INSERT INTO schools (school_name, school_code) VALUES ('Alexandra Primary School', 'P_Alexandra');
INSERT INTO schools (school_name, school_code) VALUES ('Anchor Green Primary School', 'P_Anchor');
INSERT INTO schools (school_name, school_code) VALUES ('Alexandra Primary School', 'P_Alexandra');
INSERT INTO schools (school_name, school_code) VALUES ('Anderson Primary School', 'P_Anderson');
INSERT INTO schools (school_name, school_code) VALUES ('Ang Mo Kio Primary School', 'P_Ang');
INSERT INTO schools (school_name, school_code) VALUES ('Anglo-Chinese School (Junior)', 'P_ACSJ');
INSERT INTO schools (school_name, school_code) VALUES ('Anglo-Chinese School (Primary)', 'P_ACSP');